import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import ReactQueryProvider from "./ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import SessionProvider from "./SessionProvider";
import Home from "./page";
import Login from "./(auth)/login/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={inter.className}>
          <ReactQueryDevtools initialIsOpen={false} />
          <SessionProvider session={session}>
            {!session ? <Login /> : <Home />}
          </SessionProvider>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
